kind: pipeline
name: build


steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.75.1
    buildFuture: true
    validate: true

- name: deploy
  image: appleboy/drone-scp
  settings:
    source: public/*
    target:
      from_secret: target
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    passphrase:
      from_secret: ssh_passphrase
    port:
      from_secret: ssh_port
  when:
    event:
    - promote
    target:
    - production
