variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - release
  - deploy

include:
  - project: 'infrastructure/ci-scripts'
    file: 'build-docker-image.yml'
  - project: 'infrastructure/ci-scripts'
    file: 'release-docker-image.yml'
  - project: 'infrastructure/ci-scripts'
    file: 'deploy-kubernetes.yml'

build:static:
  stage: build
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  before_script:
    - apk add --update --no-cache git
  script:
    - hugo version
    - hugo -F
  artifacts:
    paths:
      - public
  only:
    - master

build:image:
  extends: .build_image
  only:
    - master

release:image:
  extends: .release_image
  only:
    - master

deploy:
  extends: .deploy_kubernetes
  variables:
    KUBERNETES_NAMESPACE: prod
  only:
    - master
  environment:
    name: prod
