variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - release

include:
  - project: 'infrastructure/ci-scripts'
    file: 'build-docker-image.yml'
  - project: 'infrastructure/ci-scripts'
    file: 'release-docker-image.yml'

build:static:
  stage: build
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  before_script:
    - apk add --update --no-cache git
  script:
    - hugo version
    - hugo -F
  artifacts:
    paths:
      - public
  only:
    - master

build:image:
  extends: .build_image
  only:
    - master

release:image:
  extends: .release_image
  only:
    - master

# deploy:
#   stage: deploy
#   image: alpine:latest
#   before_script:
#   - apk update && apk add --no-cache openssh-client
#   - eval $(ssh-agent -s)
#   - mkdir -p ~/.ssh
#   - chmod 700 ~/.ssh
#   - echo "${SSH_PRIVATE_KEY_B64}" | base64 -d > ~/.ssh/id_rsa
#   - chmod 400 ~/.ssh/id_rsa
#   script:
#   - ssh-add -q ~/.ssh/id_rsa
#   - scp -q -o StrictHostKeyChecking=no -r public/* $SCP_DEPLOY_TARGET
#   only:
#   - master
#   dependencies:
#     - build
